load("@bazel_skylib//:bzl_library.bzl", "bzl_library")
load("//cc_module:defs.bzl", "cc_module", "cc_header_module", "cc_module_binary")

package(default_visibility = ["//visibility:public"])

cc_header_module(
    name = "iostream_hdr",
    hdr = "iostream",
    include_path = ".",
)
